default:
  image: registry.bochslerfinance.com/runners-images/dfinity-canisters:0.19.0@sha256:a7889ff2b3bc1e9d4106ba659383ffe2dd293b93c390d847d5300e6f19001cd4
  interruptible: true
  before_script:
    - dfx --version

cache:
  - key: "dfx-$CI_COMMIT_REF_SLUG"
    paths:
      - .dfx

stages:
  - build
  - test
  - prettify


build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 week

test:
  stage: test
  script:
    - echo "Running integration tests..."
    - npm run integration_test
  dependencies:
    - build
  allow_failure: false

prettify:
  stage: prettify
  script:
    - npm run prettier:check
  allow_failure: false
