[package]
name = "origyn-nft-next"
version = "0.1.4"
description = "Experimental Branch - Do not use in production. - The reference implementation for the ORIGYN NFT - Experimental Branch - Do not use in production."
repository = "https://github.com/ORIGYN_SA/origyn_nft"

[dependencies]
base = "0.8.7"
array = "https://github.com/aviate-labs/array.mo#v0.2.1"
crypto = "https://github.com/aviate-labs/crypto.mo#v0.3.1"
hash = "https://github.com/aviate-labs/hash.mo#v0.1.0"
encoding = "https://github.com/aviate-labs/encoding.mo#v0.4.1"
matchers = "https://github.com/kritzcreek/motoko-matchers#v1.3.0"
candy_0_1_10 = "https://github.com/icdevs/candy_library#v0.1.10"
candy_0_1_12 = "https://github.com/icdevs/candy_library#v0.1.12"
candy = "https://github.com/icdevs/candy_library#v0.1.12"
principalmo = "https://github.com/aviate-labs/principal.mo#v0.2.6"
ext = "https://github.com/skilesare/extendable-token#v0.1.0"
httpparser = "https://github.com/NatLabs/http-parser.mo#v0.1.2"
http = "https://github.com/aviate-labs/http.mo#v0.1.0"
json = "https://github.com/aviate-labs/json.mo#v0.2.1"
format = "https://github.com/skilesare/format.mo#v0.1.0"
stablebuffer_0_2_0 = "https://github.com/skilesare/StableBuffer#v0.2.0"
droute_client = "https://github.com/ORIGYN-SA/droute-client#v0.1.0"
map_6_0_0 = "https://github.com/ZhenyaUsenko/motoko-hash-map#v6.0.0"
map_7_0_0 = "https://github.com/ZhenyaUsenko/motoko-hash-map#v7.0.0"
map = "https://github.com/ZhenyaUsenko/motoko-hash-map#v7.0.0"
stablebuffer = "https://github.com/skilesare/StableBuffer#v0.2.0"
canistergeek = "https://github.com/ORIGYN-SA/canistergeek-motoko#nft_0_1_4"
canistergeekold = "https://github.com/ORIGYN-SA/canistergeek-motoko#main"
icrc17_kyc = "https://github.com/ORIGYN-SA/kyc.mo#master"
candy_0_2_0 = "https://github.com/icdevs/candy_library#0.2.0"
stableBTree = "https://github.com/sardariuss/MotokoStableBTree#main"